services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    environment:
        - NODE_ENV=production
        - ENABLE_SWAGGER=1
        - API_PUBLIC_URL=http://localhost:3001
    build: ./apps/api
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started

  web:
    build: ./apps/web
    env_file:
      - ./.env
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  db_data:
  minio_data:
